### ISSUE TITLE
Allow logging in to a list of Docker registries

### ISSUE THREAD

**Issue by vst** [telostat/ansible-role-teloshost#1]
The variable may read something like this:

```yaml
teloshost_docker_registries:
  - username: "username1"
    password: "password1"
    registry: "registry1.example.com"
  - username: "username2"
    password: "password2"
    registry: "registry2.example.com"
```
